var keyMirror = require('react/lib/keyMirror');

export default keyMirror({
  API_GET_LOGOUT: null,
  SUCCESS_LOGIN: null,
  ERROR_LOGIN: null,
  SUCCESS_LOGOUT: null,
  LOGIN_FAILURE_HANDLED: null,
  KEEP_ALIVE: null,

  MACHINE_STORE_CLEAR_STATE: null,
  SET_ACTIVATION_INFO: null,
  SET_USER_INFO: null,
  SET_USER_INFO_PROPERTY: null,
  SET_MACHINE_INFO: null,
  REGISTER_MACHINE_USER: null,
  SET_LOADING: null,
  UNSET_LOADING: null,
  SET_UNDER_MAINTENANCE: null,

  SCROLL_UP: null,
  SCROLL_DOWN: null,
  SET_SCROLL_STEP: null,

  SET_BILL_INFO: null,
  SET_MEMBERSHIP_INFO: null,

  SET_FEEDBACK_PROPERTY: null,
  RESET_FEEDBACK_FORM: null,

  SET_RESERVATIONS: null,
  CREATE_EMPTY: null,
  CREATE_SET_MACHINE: null,
  CREATE_SET_DATE: null,
  CREATE_SET_TIMES: null,
  CREATE_DONE: null,
  CREATE_SET_STEP: null,

  CANCEL_RESERVATION_START: null,
  CANCEL_RESERVATION_SUCCESS: null,
  CANCEL_RESERVATION_FAIL: null,

  SET_RESERVATION_RULES: null
});
