#!/bin/bash

# Exit on failures and undeclared variables

set -o errexit
set -o pipefail
set -o nounset

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"

arg1="${1:-}"

if [[ $# -eq 0 ]]
then
	echo 'Please add version as parameter'
	exit 0
fi

VERSION=$1


# Prequisites:
#
# ARM system with Linux (tested w/ Raspbian)
# sudo apt-get install exfat-fuse exfat-utils
# sudo blkid
# sudo apt-get install kpartx

sudo umount /mnt/build || true

cd ~
rm -rf build_test
mkdir build_test
cd build_test
wget --no-clobber https://downloads.raspberrypi.org/raspbian_lite_latest
unzip raspbian_lite_latest
mv *.img raspbian.img

# Mounting image
sudo kpartx -av raspbian.img
sudo mkdir -p /mnt/build
sudo mount -t ext4 /dev/mapper/loop0p2 /mnt/build

cp ~/localmachines-gateway_$VERSION.arm.deb /mnt/build/home/pi/
sudo chroot /mnt/build/ /bin/bash -c "apt-get install daemontools daemontools-run sshpass"
sudo chroot /mnt/build/ /bin/bash -c "dpkg -i /home/pi/localmachines-gateway_$VERSION.arm.deb"

sudo umount /mnt/build
sudo kpartx -dv raspbian.img

mv raspbian.img localmachines-gateway_$VERSION.img
